### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by KoltesDigital** [mattsawyer77/atom-perforce#69] opened 2016-04-14 14:18 UTC
[Enter steps to reproduce below:]
1. Open a directory in Atom, with no sub directories.
2. In this directory, create a sub directory using the Windows Explorer.

**Atom Version**: 1.7.0
**System**: Microsoft Windows�7 Entreprise 
**Thrown From**: [atom-perforce](https://github.com/mattsawyer77/atom-perforce) package, v1.7.6
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At C:\Users\jgiroux\.atom\packages\atom-perforce\lib\atom-perforce.js:147

TypeError: Cannot read property 'split' of undefined
    at Object.setupEnvironment (C:\Users\jgiroux\.atom\packages\atom-perforce\lib\atom-perforce.js:147:40)
    at execP4Command (C:\Users\jgiroux\.atom\packages\atom-perforce\lib\atom-perforce.js:44:64)
    at C:\Users\jgiroux\.atom\packages\atom-perforce\lib\atom-perforce.js:600:34
    at Array.forEach (native)
    at Object.getOpenedFiles (C:\Users\jgiroux\.atom\packages\atom-perforce\lib\atom-perforce.js:595:26)
    at Object.markOpenFiles (C:\Users\jgiroux\.atom\packages\atom-perforce\lib\atom-perforce.js:674:52)
    at MutationObserver.treeChanged (C:\Users\jgiroux\.atom\packages\atom-perforce\main.js:43:26)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "atom-perforce": {
    "autoAdd": true,
    "autoEdit": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-perforce, v1.7.6
hex, v0.6.2
jshint, v1.8.5
language-lua, v0.9.4
Sublime-Style-Column-Selection, v1.5.1

# Dev
No dev packages
```

**Comment by dander** [comment] 2016-04-14 21:00
This looks like a duplicate of #68

**Closed as completed** 2016-04-14 21:05 UTC
Labels: duplicate
